# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "github-api-app-global-lb-frontend" {
  source        = "github.com/terraform-google-modules/terraform-google-lb-http//modules/frontend?ref=v13.1.0"
  name          = "github-api-app-global-lb-frontend"
  project_id    = "designcenterhydropowerparts"
  url_map_input = module.github-api-app-global-lb-backend.backend_service_info
  depends_on    = [module.project-services-designcenterhydropowerparts, module.project-services-billing-project]
}
module "github-api-app-global-lb-backend" {
  source                  = "github.com/terraform-google-modules/terraform-google-lb-http//modules/backend?ref=v13.1.0"
  name                    = "github-api-app-global-lb-backend"
  project_id              = "designcenterhydropowerparts"
  serverless_neg_backends = [{"region" = "us-central1", "service_name" = "github-api-app-service", "type" = "cloud-run"}, {"region" = "us-east1", "service_name" = "hydro-ai-frontend-service", "type" = "cloud-run"}]
  host_path_mappings      = [{"host" = "*", "path" = "/api/*"}, {"host" = "*", "path" = "/*"}]
  depends_on              = [module.project-services-designcenterhydropowerparts, module.project-services-billing-project]
}
module "github-api-app-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.2"
  project_id                    = "designcenterhydropowerparts"
  location                      = "us-central1"
  service_name                  = "github-api-app-service"
  containers                    = [{"container_image" = "gcr.io/cloudrun/hello", "container_name" = "service-container", "env_secret_vars" = {"github_api_db_secret_SECRET" = module.github-api-db-secret.env_vars.SECRET}, "env_vars" = {"github_api_db_CLOUD_SQL_DATABASE_CONNECTION_NAME" = module.github-api-db.instance_connection_name, "github_api_db_CLOUD_SQL_DATABASE_HOST" = module.github-api-db.instance_first_ip_address, "github_api_db_CLOUD_SQL_DATABASE_NAME" = module.github-api-db.env_vars.CLOUD_SQL_DATABASE_NAME}, "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/cloudsql.instanceUser", "roles/cloudsql.client"], ["roles/secretmanager.secretAccessor"])
  ingress                       = "INGRESS_TRAFFIC_ALL"
  members                       = ["allUsers"]
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-designcenterhydropowerparts, module.project-services-billing-project]
}
module "cfd-compute-engine" {
  source        = "github.com/terraform-google-modules/terraform-google-vm//modules/instance_template?ref=v13.5.0"
  project_id    = "designcenterhydropowerparts"
  region        = "us-central1"
  name_prefix   = "cfd-simulator"
  machine_type  = "n2d-standard-128"
  network       = "default"
  access_config = [{"nat_ip" = null, "network_tier" = "PREMIUM"}]
  depends_on    = [module.project-services-designcenterhydropowerparts, module.project-services-billing-project]
}
module "cfd-simulation-results" {
  source     = "github.com/terraform-google-modules/terraform-google-cloud-storage//modules/simple_bucket?ref=v11.1.2"
  project_id = "designcenterhydropowerparts"
  location   = "us-central1"
  name       = "cfd-simulation-results"
  iam_members = [{
    member = module.cfd-compute-engine.service_account_info.member
    role   = "roles/storage.objectAdmin"
  }]
  storage_class = "STANDARD"
  depends_on    = [module.project-services-designcenterhydropowerparts, module.project-services-billing-project]
}
module "hydro-ai-frontend-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.2"
  project_id                    = "designcenterhydropowerparts"
  location                      = "us-east1"
  service_name                  = "hydro-ai-frontend-service"
  containers                    = [{"container_image" = "gcr.io/cloudrun/hello", "env_vars" = {"hydro_ai_gemini_proxy_SERVICE_ENDPOINT" = module.hydro-ai-gemini-proxy.service_uri}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = ["roles/run.invoker"]
  ingress                       = "INGRESS_TRAFFIC_ALL"
  members                       = ["allUsers"]
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-designcenterhydropowerparts, module.project-services-billing-project]
}
module "hydro-ai-static-assets" {
  source     = "github.com/terraform-google-modules/terraform-google-cloud-storage//modules/simple_bucket?ref=v11.1.2"
  project_id = "designcenterhydropowerparts"
  location   = "us-central1"
  name       = "hydro-ai-static-assets"
  iam_members = [{
    member = module.hydro-ai-frontend-service.service_account_id.member
    role   = "roles/storage.objectAdmin"
  }]
  storage_class = "STANDARD"
  depends_on    = [module.project-services-designcenterhydropowerparts, module.project-services-billing-project]
}
module "hydro-ai-gemini-proxy" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.2"
  project_id                    = "designcenterhydropowerparts"
  location                      = "us-central1"
  service_name                  = "hydro-ai-gemini-proxy"
  containers                    = [{"container_image" = "gcr.io/cloudrun/hello"}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = ["roles/aiplatform.user"]
  ingress                       = "INGRESS_TRAFFIC_ALL"
  members                       = ["allUsers"]
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  service_labels = {
    hydro_ai_vertex_ai_vertex-ai = "true"
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-designcenterhydropowerparts, module.project-services-billing-project]
}
module "hydro-ai-vertex-ai" {
  source        = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.0.0"
  project_id    = "designcenterhydropowerparts"
  activate_apis = ["aiplatform.googleapis.com"]
  depends_on    = [module.project-services-designcenterhydropowerparts, module.project-services-billing-project]
}
module "github-api-db" {
  source                      = "github.com/terraform-google-modules/terraform-google-sql-db//modules/postgresql?ref=v26.2.1"
  project_id                  = "designcenterhydropowerparts"
  region                      = "us-central1"
  name                        = "github-api-db"
  edition                     = "ENTERPRISE_PLUS"
  database_version            = "POSTGRES_15"
  availability_type           = "REGIONAL"
  deletion_protection         = false
  database_flags              = [{"name" = "cloudsql.iam_authentication", "value" = "on"}]
  data_cache_enabled          = true
  tier                        = "db-perf-optimized-N-8"
  deletion_protection_enabled = false
  disk_autoresize             = true
  backup_configuration = {
    enabled                        = true
    point_in_time_recovery_enabled = true
  }
  iam_users = [{
    email = module.github-api-app-service.service_account_id.email
    id    = module.github-api-app-service.service_account_id.id
    type  = "CLOUD_IAM_SERVICE_ACCOUNT"
  }]
  depends_on = [module.project-services-designcenterhydropowerparts, module.project-services-billing-project]
}
module "github-api-db-secret" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "designcenterhydropowerparts"
  name        = "github-api-db-secret"
  secret_data = module.github-api-db.generated_user_password
  depends_on  = [module.project-services-designcenterhydropowerparts, module.project-services-billing-project]
}
module "apphub" {
  source         = "github.com/GoogleCloudPlatform/terraform-google-apphub?ref=v0.3.0"
  project_id     = var.apphub_project_id
  location       = var.apphub_location
  service_uris   = concat(module.github-api-app-global-lb-frontend.apphub_service_uri, module.github-api-app-global-lb-backend.apphub_service_uri, [module.github-api-app-service.apphub_service_uri], [module.cfd-simulation-results.apphub_service_uri], [module.hydro-ai-frontend-service.apphub_service_uri], [module.hydro-ai-static-assets.apphub_service_uri], [module.hydro-ai-gemini-proxy.apphub_service_uri], [module.github-api-db.apphub_service_uri])
  application_id = var.apphub_application_id
}
module "project-services-designcenterhydropowerparts" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v17.1.0"
  project_id                  = "designcenterhydropowerparts"
  disable_services_on_destroy = false
  activate_apis               = []
}
module "project-services-billing-project" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v17.1.0"
  project_id                  = "designcenterhydropowerparts"
  disable_services_on_destroy = false
  activate_apis               = ["apphub.googleapis.com", "cloudresourcemanager.googleapis.com"]
}